server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api
  port: '8494'
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer